site_name: No BS Vegan Recipes

nav:
  - Home: index.md
  - Bakery:
    - Bread:
      - Banana Bread: banana-bread.md
    - Cakes:
      - Apple Cider Cake: apple-cider-cake.md
      - Biscoff Marble Cake: biscoff-marble-cake-1.md
      - Cheesecake with Chocolate Crust: cheesecake-with-chocolate-crust.md
      - Classic Cheesecake: classic-cheesecake.md
      - Dirt Cake: dirt-cake.md
      - Lemon Cake: lemon-cake.md
      - Pumpkin Cake: pumpkin-cake.md
      - Red Velvet Cake: red-velvet-cake.md
      - Vanilla Cake: vanilla-cake.md
    - Cookies:
      - Chocolate Chip Cookies (Original): chocolate-chip-cookies.md
      - Ginger Cookies: ginger-cookies.md
      - Gingerbread Cookies: gingerbread-cookies.md
      - Halloween Gingerbread Cookies: halloween-gingerbread-skeleton-cookies.md
      - Peanut Butter Cookies: peanut-butter-cookies.md
      - Pumpkin Cookies: pumpkin-cookies.md
      - Sugar Cookies: sugar-cookies.md
    - Cupcakes:
      - Funfetti Cupcakes: funfetti-cupcakes.md
    - Pies:
      - Peanut Butter Pie: peanut-butter-pie.md
      - Pecan Pie: pecan-pie.md
      - Pumpkin Pie: pumpkin-pie.md
    - Other:
      - Lemon Bars: lemon-bars.md
      - Meringue Ghosts: meringue-ghosts.md
  - Entrees:
    - Indian Chicken Curry: indian-chicken-curry.md
    - Seitan Saltado (Peruvian Stir-Fry with Potatoes): seitan-saltado.md
  - SaucesandSpreads:
    - Barbecue Sauce : barbecue-sauce.md
  - Drinks:
    - Blood Orange Blackberry Rum Punch: blood-orange-blackberry-rum-punch.md

theme:
  name: material
  palette:
    primary: teal
    accent: deep purple
  font: false

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.smartsymbols
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
